"""initial migration

Revision ID: 85529d7066a1
Revises: 
Create Date: 2023-01-10 18:40:04.726356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85529d7066a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_rest_metabolic_rate', sa.Integer(), nullable=True))
        batch_op.drop_column('new_rest_meta_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_rest_meta_rate', sa.INTEGER(), nullable=True))
        batch_op.drop_column('new_rest_metabolic_rate')

    # ### end Alembic commands ###
